In [96]:
#Mini projeto modelagem de dados - importação e tratamento de base de dados do varejo
# sprint 01 >>   Objetivo: importar a base Varejo.csv   https://www.kaggle.com/datasets/namespaiva/base-varejo/data  no Google Colab e conhecer sua estrutura antes de realizar qualquer alteração.
#Atividades:
#Criar e nomear o notebook no Google Colab.
#Importar a biblioteca pandas.
#Fazer upload do arquivo Varejo.csv.
#Carregar a base em um DataFrame.
#Mostrar as primeiras linhas.
#Apresentar os nomes das colunas.
#Verificar os tipos de dados.
#Gerar o resumo da base com df.info().


In [97]:
# Importação da biblioteca pandas para leitura, organização e análise dos dados
import pandas as pd

print("Biblioteca pandas importada com sucesso!")

Biblioteca pandas importada com sucesso!


In [98]:
# Instala a biblioteca oficial de integração com o Kaggle
!pip install -q kagglehub

# Importa as bibliotecas necessárias
import kagglehub
import os

# Baixa a base diretamente do Kaggle para o Google Colab
pasta_base = kagglehub.dataset_download(
    "namespaiva/base-varejo",
    output_dir="/content/base_varejo"
)

# Mostra onde a base foi salva
print("Base baixada na pasta:", pasta_base)

# Mostra os arquivos encontrados
print("\nArquivos disponíveis:")
print(os.listdir(pasta_base))

Using Colab cache for faster access to the 'base-varejo' dataset.
Base baixada na pasta: /kaggle/input/base-varejo

Arquivos disponíveis:
['Base Varejo.csv', 'Projeto III - Anlise Exploratria de Dados Utilizando o Python ou RStudio.pdf']


In [99]:
# Define o caminho do arquivo CSV baixado do Kaggle
caminho_arquivo = "/content/base_varejo/Base Varejo.csv"

# Carrega a base em um DataFrame chamado df
# sep=None permite que o pandas identifique automaticamente o separador
df = pd.read_csv(
    caminho_arquivo,
    sep=None,
    engine="python"
)

# Confirma que a base foi carregada
print("Base carregada com sucesso!")

Base carregada com sucesso!


In [100]:
# Exibe as cinco primeiras linhas para conferir a organização da base
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN


In [101]:
# Mostra a quantidade de linhas e colunas da base
print("Número de registros:", df.shape[0])
print("Número de colunas:", df.shape[1])

Número de registros: 830000
Número de colunas: 14


In [102]:
# Mostra o nome de todas as colunas da base
print("COLUNAS DA BASE:")
print(df.columns.tolist())

# Mostra o tipo de dado identificado em cada coluna
print("\nTIPOS DE DADOS:")
print(df.dtypes)

COLUNAS DA BASE:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

TIPOS DE DADOS:
DATA            object
CO_ID            int64
CL_ID            int64
CL_GENERO       object
CL_EC            int64
CL_FHL           int64
CL_SEG          object
PR_ID            int64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object


In [103]:
# Exibe o resumo técnico da base:
# quantidade de registros, valores não nulos e tipos de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   DATA         830000 non-null  object 
 1   CO_ID        830000 non-null  int64  
 2   CL_ID        830000 non-null  int64  
 3   CL_GENERO    830000 non-null  object 
 4   CL_EC        830000 non-null  int64  
 5   CL_FHL       830000 non-null  int64  
 6   CL_SEG       830000 non-null  object 
 7   PR_ID        830000 non-null  int64  
 8   PR_CAT       830000 non-null  object 
 9   PR_NOME      830000 non-null  object 
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB


## Diagnóstico inicial da base

A base Varejo.csv foi importada diretamente do Kaggle e carregada com a biblioteca pandas.

- Número de registros: 830.000
- Número total de colunas: 14
- Colunas com dados: 10
- Colunas totalmente vazias: Unnamed: 10, Unnamed: 11, Unnamed: 12 e Unnamed: 13
- A coluna DATA foi inicialmente reconhecida como texto (object).
- As colunas principais não apresentaram valores nulos neste diagnóstico inicial.
- As colunas vazias e o tipo da coluna DATA serão tratados nas próximas etapas.

In [104]:
#Sprint 2 – Diagnóstico e ajuste dos tipos de dados
#Atividades:
#Identificar os tipos atuais das colunas.
#Padronizar os nomes das colunas.
#Remover espaços desnecessários dos textos.
#Verificar categorias vazias ou escritas de maneiras diferentes.
#Converter a coluna de data para datetime.
#Converter colunas numéricas que estejam armazenadas como texto.
#Identificar datas inválidas geradas durante a conversão.
#Conferir os tipos depois dos ajustes.
# Mostra o tipo atual de cada coluna antes das transformações
tipos_antes = df.dtypes.to_frame(name="Tipo atual")

print("TIPOS DE DADOS ANTES DOS AJUSTES")
display(tipos_antes)

TIPOS DE DADOS ANTES DOS AJUSTES


,Tipo atual
DATA,object
CO_ID,int64
CL_ID,int64
CL_GENERO,object
CL_EC,int64
CL_FHL,int64
CL_SEG,object
PR_ID,int64
PR_CAT,object
PR_NOME,object


In [105]:
# Padroniza os nomes das colunas:
# remove espaços nas extremidades, converte para maiúsculas,
# substitui espaços por "_" e remove o caractere ":"

df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(" ", "_", regex=False)
    .str.replace(":", "", regex=False)
)

# Mostra os nomes depois da padronização
print("COLUNAS APÓS A PADRONIZAÇÃO:")
print(df.columns.tolist())

COLUNAS APÓS A PADRONIZAÇÃO:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'UNNAMED_10', 'UNNAMED_11', 'UNNAMED_12', 'UNNAMED_13']


In [106]:
# Colunas que contêm textos ou categorias
colunas_texto = ["CL_GENERO", "CL_SEG", "PR_CAT", "PR_NOME"]

# Remove espaços desnecessários e converte os textos para maiúsculas
for coluna in colunas_texto:
    df[coluna] = df[coluna].str.strip().str.upper()

print("Textos padronizados com sucesso!")

Textos padronizados com sucesso!


In [107]:
# Verifica a quantidade de categorias, valores nulos e textos vazios
for coluna in colunas_texto:
    print("\nCOLUNA:", coluna)
    print("Categorias diferentes:", df[coluna].nunique())
    print("Valores nulos:", df[coluna].isnull().sum())
    print("Textos vazios:", (df[coluna] == "").sum())

    print("Valores mais frequentes:")
    print(df[coluna].value_counts(dropna=False).head(10))
    print("-" * 50)


COLUNA: CL_GENERO
Categorias diferentes: 2
Valores nulos: 0
Textos vazios: 0
Valores mais frequentes:
CL_GENERO
F    432576
M    397424
Name: count, dtype: int64
--------------------------------------------------

COLUNA: CL_SEG
Categorias diferentes: 3
Valores nulos: 0
Textos vazios: 0
Valores mais frequentes:
CL_SEG
B    530163
C    232101
A     67736
Name: count, dtype: int64
--------------------------------------------------

COLUNA: PR_CAT
Categorias diferentes: 7
Valores nulos: 0
Textos vazios: 0
Valores mais frequentes:
PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64
--------------------------------------------------

COLUNA: PR_NOME
Categorias diferentes: 118
Valores nulos: 0
Textos vazios: 0
Valores mais frequentes:
PR_NOME
PRESUNTO COZIDO       14381
SARDINHA               7490
GEL                    7399
BANANA                 7385
DESENGORDURA

A verificação encontrou uma inconsistência relevante:

CL_GENERO: 2 categorias válidas (F e M);
CL_SEG: 3 categorias válidas (A, B e C);
PR_CAT: contém 3.650 registros com #N/D, que representam uma categoria não informada;
PR_NOME: possui 118 produtos diferentes;
não existem textos vazios nem nulos reconhecidos pelo pandas nas colunas textuais.

O valor #N/D ainda não aparece como nulo porque está armazenado como texto. Vamos tratá-lo na Sprint 3.

In [108]:
# Mostra uma amostra dos valores originais da coluna DATA
print("EXEMPLOS DE DATAS DA BASE:")
print(df["DATA"].head(10).tolist())

EXEMPLOS DE DATAS DA BASE:
['01/02/2019', '01/02/2019', '01/02/2019', '01/02/2019', '01/02/2019', '01/02/2019', '01/02/2019', '01/02/2019', '01/02/2019', '01/02/2019']


In [109]:
# Guarda uma cópia das datas originais para conferência
datas_originais = df["DATA"].copy()

# Converte a coluna DATA de texto para o tipo datetime
# O formato %d/%m/%Y representa dia/mês/ano
# errors="coerce" transforma datas inválidas em NaT
df["DATA"] = pd.to_datetime(
    df["DATA"],
    format="%d/%m/%Y",
    errors="coerce"
)

# Mostra o novo tipo da coluna e alguns exemplos
print("Novo tipo da coluna DATA:", df["DATA"].dtype)
print("\nPrimeiras datas convertidas:")
print(df["DATA"].head())

Novo tipo da coluna DATA: datetime64[ns]

Primeiras datas convertidas:
0   2019-02-01
1   2019-02-01
2   2019-02-01
3   2019-02-01
4   2019-02-01
Name: DATA, dtype: datetime64[ns]


In [110]:
# Conta quantas datas se tornaram NaT durante a conversão
quantidade_datas_invalidas = df["DATA"].isna().sum()

print("Quantidade de datas inválidas:", quantidade_datas_invalidas)

# Se existirem datas inválidas, mostra os valores originais
if quantidade_datas_invalidas > 0:
    print("\nExemplos de valores inválidos:")
    print(
        datas_originais[df["DATA"].isna()]
        .value_counts()
        .head(10)
    )
else:
    print("Nenhuma data inválida foi encontrada.")

Quantidade de datas inválidas: 0
Nenhuma data inválida foi encontrada.


### Conversão e validação das datas

A coluna DATA estava armazenada como texto e foi convertida para o tipo datetime, utilizando o formato dia/mês/ano. A conversão não identificou datas inválidas, pois nenhum registro foi transformado em NaT.

In [111]:
# Colunas que devem possuir valores numéricos
colunas_numericas = ["CO_ID", "CL_ID", "CL_EC", "CL_FHL", "PR_ID"]

# Garante que essas colunas estejam armazenadas como números
for coluna in colunas_numericas:
    df[coluna] = pd.to_numeric(df[coluna], errors="coerce")

# Mostra os tipos após a verificação
print("TIPOS DAS COLUNAS NUMÉRICAS:")
print(df[colunas_numericas].dtypes)

# Verifica se a conversão gerou valores nulos
print("\nNULOS NAS COLUNAS NUMÉRICAS:")
print(df[colunas_numericas].isnull().sum())

TIPOS DAS COLUNAS NUMÉRICAS:
CO_ID     int64
CL_ID     int64
CL_EC     int64
CL_FHL    int64
PR_ID     int64
dtype: object

NULOS NAS COLUNAS NUMÉRICAS:
CO_ID     0
CL_ID     0
CL_EC     0
CL_FHL    0
PR_ID     0
dtype: int64


In [112]:
# Exibe os tipos de dados após os ajustes realizados na Sprint 2
print("TIPOS DE DADOS APÓS OS AJUSTES:")
print(df.dtypes)

TIPOS DE DADOS APÓS OS AJUSTES:
DATA          datetime64[ns]
CO_ID                  int64
CL_ID                  int64
CL_GENERO             object
CL_EC                  int64
CL_FHL                 int64
CL_SEG                object
PR_ID                  int64
PR_CAT                object
PR_NOME               object
UNNAMED_10           float64
UNNAMED_11           float64
UNNAMED_12           float64
UNNAMED_13           float64
dtype: object


## Resultado da Sprint 2 — Ajuste dos tipos de dados

- Os nomes das colunas foram padronizados.
- Os valores das colunas textuais foram convertidos para letras maiúsculas e tiveram os espaços desnecessários removidos.
- As colunas CL_GENERO e CL_SEG não apresentaram categorias vazias ou inconsistentes.
- A coluna PR_CAT apresentou 3.650 registros com o valor #N/D, que serão tratados como informação ausente na próxima sprint.
- A coluna DATA foi convertida de object para datetime64[ns].
- Não foram identificadas datas inválidas.
- As colunas numéricas foram verificadas e permaneceram como int64, sem geração de valores nulos.
- As quatro colunas UNNAMED continuam vazias e serão removidas na etapa de limpeza.

In [113]:
#Sprint 3 – Tratamento de nulos, duplicatas e inconsistências
#Atividades:
#Contar os valores nulos de cada coluna.
#Identificar registros duplicados.
#Verificar categorias vazias ou inconsistentes.
#Definir se os valores nulos serão removidos ou preenchidos.
#Explicar a escolha realizada para tratar os valores nulos.
#Eliminar duplicatas relevantes.
#Conferir o resultado da limpeza.
#Criar o DataFrame limpo.
#Resultado esperado:
#Base sem duplicatas relevantes, com os valores nulos tratados e com as decisões de limpeza explicadas no notebook.

# Conta a quantidade de valores nulos em cada coluna
nulos_por_coluna = df.isnull().sum()

# Calcula o percentual de valores nulos
percentual_nulos = (df.isnull().sum() / len(df) * 100).round(2)

# Reúne os resultados em uma tabela
relatorio_nulos = pd.DataFrame({
    "Quantidade de nulos": nulos_por_coluna,
    "Percentual de nulos": percentual_nulos
})

print("VALORES NULOS POR COLUNA:")
display(relatorio_nulos)

VALORES NULOS POR COLUNA:


,Quantidade de nulos,Percentual de nulos
DATA,0,0.0
CO_ID,0,0.0
CL_ID,0,0.0
CL_GENERO,0,0.0
CL_EC,0,0.0
CL_FHL,0,0.0
CL_SEG,0,0.0
PR_ID,0,0.0
PR_CAT,0,0.0
PR_NOME,0,0.0


In [114]:
# Conta registros completamente duplicados
quantidade_duplicatas = df.duplicated().sum()

print("Quantidade de registros duplicados:", quantidade_duplicatas)

# Mostra alguns exemplos, caso existam duplicatas
if quantidade_duplicatas > 0:
    print("\nExemplos de registros duplicados:")
    display(df[df.duplicated(keep=False)].head(10))
else:
    print("Nenhum registro completamente duplicado foi encontrado.")

Quantidade de registros duplicados: 96553

Exemplos de registros duplicados:


,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,UNNAMED_10,UNNAMED_11,UNNAMED_12,UNNAMED_13
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
7,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,2019-02-01,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
19,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
22,2019-02-01,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMAO,NaN,NaN,NaN,NaN
34,2019-02-01,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
40,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,2019-02-01,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMAO,NaN,NaN,NaN,NaN


### Diagnóstico das duplicatas

Foram encontrados 96.553 registros completamente duplicados. Para fins deste mini-projeto, os registros integralmente idênticos serão considerados duplicatas relevantes e removidos.

A base não possui identificador da transação, número da nota fiscal ou quantidade comprada. Por isso, existe a possibilidade de algumas repetições representarem compras legítimas de mais de uma unidade do mesmo produto. Essa limitação será registrada nas conclusões do projeto.

In [115]:
# Verifica textos vazios e valores usados para representar ausência de informação
for coluna in colunas_texto:
    quantidade_vazios = (df[coluna] == "").sum()
    quantidade_nd = (df[coluna] == "#N/D").sum()

    print(
        coluna,
        "| Textos vazios:", quantidade_vazios,
        "| Valores #N/D:", quantidade_nd
    )

CL_GENERO | Textos vazios: 0 | Valores #N/D: 0
CL_SEG | Textos vazios: 0 | Valores #N/D: 0
PR_CAT | Textos vazios: 0 | Valores #N/D: 3650
PR_NOME | Textos vazios: 0 | Valores #N/D: 3650


### Decisão sobre o tratamento dos valores ausentes

Foram adotadas as seguintes decisões:

1. As colunas UNNAMED_10, UNNAMED_11, UNNAMED_12 e UNNAMED_13 serão removidas, pois estão 100% vazias e não possuem informação útil.

2. Os 3.650 valores #N/D encontrados na coluna PR_CAT serão substituídos pela categoria NÃO INFORMADO.

3. Optou-se por não excluir as linhas com #N/D porque as demais informações desses registros, como data, cliente, produto e segmento, continuam úteis para a análise.

4. Não será atribuída uma categoria específica aos registros #N/D, pois isso exigiria uma suposição sobre os dados. A expressão NÃO INFORMADO preserva os registros sem criar uma informação que não estava na base original.

5. As demais colunas principais não apresentaram valores nulos e, portanto, não precisam de remoção ou preenchimento.

In [116]:
# Cria uma cópia da base para aplicar a limpeza
# A base original df permanece preservada
df_limpo = df.copy()

# Lista das colunas completamente vazias
colunas_vazias = [
    "UNNAMED_10",
    "UNNAMED_11",
    "UNNAMED_12",
    "UNNAMED_13"
]

# Remove as colunas 100% vazias
df_limpo = df_limpo.drop(columns=colunas_vazias)

# Substitui #N/D por uma categoria explícita
df_limpo["PR_CAT"] = df_limpo["PR_CAT"].replace(
    "#N/D",
    "NÃO INFORMADO"
)

# Confere o resultado
print("Quantidade de colunas após a remoção:", df_limpo.shape[1])
print(
    "Registros classificados como NÃO INFORMADO:",
    (df_limpo["PR_CAT"] == "NÃO INFORMADO").sum()
)
print(
    "Total de valores nulos na base:",
    df_limpo.isnull().sum().sum()
)

Quantidade de colunas após a remoção: 10
Registros classificados como NÃO INFORMADO: 3650
Total de valores nulos na base: 0


In [117]:
# Registra a quantidade de linhas antes da remoção
registros_antes = len(df_limpo)

# Remove registros completamente duplicados
# reset_index reorganiza a numeração das linhas
df_limpo = df_limpo.drop_duplicates().reset_index(drop=True)

# Calcula os resultados
registros_depois = len(df_limpo)
duplicatas_removidas = registros_antes - registros_depois

print("Registros antes da limpeza:", registros_antes)
print("Duplicatas removidas:", duplicatas_removidas)
print("Registros após a limpeza:", registros_depois)

Registros antes da limpeza: 830000
Duplicatas removidas: 96553
Registros após a limpeza: 733447


In [118]:
# Conferência final da base limpa
print("CONFERÊNCIA DA BASE LIMPA")
print("-" * 40)

print("Número de registros:", df_limpo.shape[0])
print("Número de colunas:", df_limpo.shape[1])
print("Total de valores nulos:", df_limpo.isnull().sum().sum())
print("Total de duplicatas:", df_limpo.duplicated().sum())
print(
    "Valores #N/D restantes:",
    (df_limpo["PR_CAT"] == "#N/D").sum()
)
print(
    "Valores NÃO INFORMADO:",
    (df_limpo["PR_CAT"] == "NÃO INFORMADO").sum()
)

print("\nColunas da base limpa:")
print(df_limpo.columns.tolist())

print("\nTipos de dados:")
print(df_limpo.dtypes)

CONFERÊNCIA DA BASE LIMPA
----------------------------------------
Número de registros: 733447
Número de colunas: 10
Total de valores nulos: 0
Total de duplicatas: 0
Valores #N/D restantes: 0
Valores NÃO INFORMADO: 3228

Colunas da base limpa:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']

Tipos de dados:
DATA         datetime64[ns]
CO_ID                 int64
CL_ID                 int64
CL_GENERO            object
CL_EC                 int64
CL_FHL                int64
CL_SEG               object
PR_ID                 int64
PR_CAT               object
PR_NOME              object
dtype: object


## Resultado da Sprint 3 — Limpeza dos dados

- A base original possuía 830.000 registros e 14 colunas.
- Foram removidas quatro colunas completamente vazias.
- Os 3.650 registros originalmente identificados como #N/D em PR_CAT foram classificados como NÃO INFORMADO.
- Foram removidos 96.553 registros completamente duplicados.
- Após a retirada das duplicatas, permaneceram 3.228 registros únicos na categoria NÃO INFORMADO.
- A base limpa ficou com 733.447 registros e 10 colunas.
- A base limpa não possui valores nulos nem registros completamente duplicados.
- O DataFrame tratado foi armazenado na variável df_limpo.

In [119]:
#Sprint 4 – Estatística descritiva e agrupamentos
#Atividades:
#Identificar a coluna de número de filhos.
#Calcular média, mediana, desvio padrão e moda.
#Calcular os valores máximo e mínimo.
#Contar os registros válidos da coluna.
#Criar pelo menos dois agrupamentos com groupby() ou pivot_table().
#Comparar os resultados obtidos.
#Registrar uma breve interpretação dos resultados.
#Resultado esperado:
#Estatísticas obrigatórias calculadas e pelo menos dois agrupamentos apresentados e interpretados no notebook.

# Confere a coluna que representa o número de filhos dos clientes
print("COLUNA ANALISADA: CL_FHL")
print("Tipo de dado:", df_limpo["CL_FHL"].dtype)
print("Valores nulos:", df_limpo["CL_FHL"].isnull().sum())

print("\nDistribuição dos registros por número de filhos:")
print(
    df_limpo["CL_FHL"]
    .value_counts()
    .sort_index()
)

COLUNA ANALISADA: CL_FHL
Tipo de dado: int64
Valores nulos: 0

Distribuição dos registros por número de filhos:
CL_FHL
0    384986
1     90845
2     94168
3     92407
4     71041
Name: count, dtype: int64


In [120]:
# Seleciona a coluna referente ao número de filhos
filhos = df_limpo["CL_FHL"]

# Calcula as estatísticas descritivas exigidas
estatisticas_filhos = pd.DataFrame({
    "Estatística": [
        "Média",
        "Mediana",
        "Desvio padrão",
        "Moda",
        "Máximo",
        "Mínimo",
        "Contagem"
    ],
    "Resultado": [
        filhos.mean(),
        filhos.median(),
        filhos.std(),
        filhos.mode().iloc[0],
        filhos.max(),
        filhos.min(),
        filhos.count()
    ]
})

# Arredonda os resultados para duas casas decimais
estatisticas_filhos["Resultado"] = (
    estatisticas_filhos["Resultado"].round(2)
)

print("ESTATÍSTICAS DO NÚMERO DE FILHOS")
display(estatisticas_filhos)

ESTATÍSTICAS DO NÚMERO DE FILHOS


,Estatística,Resultado
0,Média,1.15
1,Mediana,0.00
2,Desvio padrão,1.42
3,Moda,0.00
4,Máximo,4.00
5,Mínimo,0.00
6,Contagem,733447.00


### Estatísticas descritivas do número de filhos

- Média: 1,15 filho por registro.
- Mediana: 0 filho.
- Desvio padrão: 1,42.
- Moda: 0 filho.
- Máximo: 4 filhos.
- Mínimo: 0 filho.
- Contagem: 733.447 registros válidos.

A média indica que os registros correspondem, em média, a clientes com aproximadamente 1,15 filho. A mediana e a moda iguais a zero demonstram que os clientes sem filhos representam o grupo mais frequente da base.

Como a base registra compras e um mesmo cliente pode aparecer várias vezes, essas estatísticas representam os registros de compras, e não necessariamente a distribuição de clientes únicos.

In [121]:
# Agrupa os registros de compras por gênero
compras_por_genero = (
    df_limpo
    .groupby("CL_GENERO")
    .size()
    .reset_index(name="QUANTIDADE_COMPRAS")
)

# Calcula a participação percentual de cada gênero
compras_por_genero["PERCENTUAL"] = (
    compras_por_genero["QUANTIDADE_COMPRAS"]
    / compras_por_genero["QUANTIDADE_COMPRAS"].sum()
    * 100
).round(2)

# Ordena do maior para o menor
compras_por_genero = compras_por_genero.sort_values(
    by="QUANTIDADE_COMPRAS",
    ascending=False
)

print("COMPRAS POR GÊNERO")
display(compras_por_genero)

COMPRAS POR GÊNERO


,CL_GENERO,QUANTIDADE_COMPRAS,PERCENTUAL
0,F,382427,52.14
1,M,351020,47.86


### Agrupamento 1 — Compras por gênero

O gênero feminino apresentou 382.427 registros de compras, correspondendo a 52,14% da base limpa. O gênero masculino apresentou 351.020 registros, representando 47,86%.

Portanto, o gênero feminino possui a maior quantidade de compras registradas, com 31.407 registros a mais que o gênero masculino. Apesar dessa diferença, a distribuição das compras entre os gêneros é relativamente equilibrada.

In [122]:
# Agrupa os registros de compras por categoria de produto
compras_por_categoria = (
    df_limpo
    .groupby("PR_CAT")
    .size()
    .reset_index(name="QUANTIDADE_COMPRAS")
)

# Calcula a participação percentual de cada categoria
compras_por_categoria["PERCENTUAL"] = (
    compras_por_categoria["QUANTIDADE_COMPRAS"]
    / compras_por_categoria["QUANTIDADE_COMPRAS"].sum()
    * 100
).round(2)

# Ordena da categoria com mais compras para a com menos compras
compras_por_categoria = compras_por_categoria.sort_values(
    by="QUANTIDADE_COMPRAS",
    ascending=False
)

print("COMPRAS POR CATEGORIA DE PRODUTO")
display(compras_por_categoria)

COMPRAS POR CATEGORIA DE PRODUTO


,PR_CAT,QUANTIDADE_COMPRAS,PERCENTUAL
1,ALIMENTOS,384197,52.38
3,HIGIENE,137702,18.77
4,LIMPEZA,128632,17.54
2,BEBIDAS,38264,5.22
6,PET,28553,3.89
0,ACESSORIOS,12871,1.75
5,NÃO INFORMADO,3228,0.44


### Agrupamento 2 — Compras por categoria de produto

A categoria Alimentos apresentou 384.197 registros, correspondendo a 52,38% das compras da base limpa. Em seguida aparecem Higiene, com 18,77%, e Limpeza, com 17,54%.

As três principais categorias — Alimentos, Higiene e Limpeza — representam aproximadamente 88,69% dos registros de compras. Isso demonstra uma forte concentração das compras em produtos considerados essenciais.

A categoria Acessórios apresentou a menor participação entre as categorias identificadas, com 1,75%. Os registros classificados como NÃO INFORMADO representam apenas 0,44% da base limpa.
Os 3.228 registros classificados como NÃO INFORMADO representam apenas 0,44% da base limpa. Por se tratar de uma participação reduzida, esse grupo possui impacto limitado sobre os resultados gerais e não altera a ordem das categorias mais compradas. Ainda assim, sua existência foi registrada como uma limitação da qualidade dos dados.


In [123]:
# Agrupa os registros de compras por segmento de cliente
compras_por_segmento = (
    df_limpo
    .groupby("CL_SEG")
    .size()
    .reset_index(name="QUANTIDADE_COMPRAS")
)

# Calcula a participação percentual de cada segmento
compras_por_segmento["PERCENTUAL"] = (
    compras_por_segmento["QUANTIDADE_COMPRAS"]
    / compras_por_segmento["QUANTIDADE_COMPRAS"].sum()
    * 100
).round(2)

# Ordena do segmento com mais compras para o menor
compras_por_segmento = compras_por_segmento.sort_values(
    by="QUANTIDADE_COMPRAS",
    ascending=False
)

print("COMPRAS POR SEGMENTO DE CLIENTE")
display(compras_por_segmento)

COMPRAS POR SEGMENTO DE CLIENTE


,CL_SEG,QUANTIDADE_COMPRAS,PERCENTUAL
1,B,468505,63.88
2,C,205265,27.99
0,A,59677,8.14


### Análise complementar — Compras por segmento de cliente

O segmento B apresentou 468.505 registros de compras, correspondendo a 63,88% da base limpa. O segmento C representou 27,99%, enquanto o segmento A apresentou participação de 8,14%.

Os segmentos B e C, juntos, concentram 91,87% das compras registradas. O resultado demonstra que as compras estão fortemente concentradas no segmento B.

A base não apresenta a descrição dos critérios utilizados para classificar os clientes nos segmentos A, B e C. Portanto, é possível analisar a participação de cada grupo, mas não atribuir características comerciais ou socioeconômicas a esses segmentos.

In [124]:
# Cria o ranking dos produtos com mais registros de compras
produtos_mais_comprados = (
    df_limpo
    .groupby("PR_NOME")
    .size()
    .reset_index(name="QUANTIDADE_COMPRAS")
    .sort_values(
        by="QUANTIDADE_COMPRAS",
        ascending=False
    )
    .head(10)
)

# Calcula a participação de cada produto na base completa
produtos_mais_comprados["PERCENTUAL_DA_BASE"] = (
    produtos_mais_comprados["QUANTIDADE_COMPRAS"]
    / len(df_limpo)
    * 100
).round(2)

# Reorganiza a numeração do ranking
produtos_mais_comprados = produtos_mais_comprados.reset_index(drop=True)
produtos_mais_comprados.index = produtos_mais_comprados.index + 1

print("DEZ PRODUTOS MAIS COMPRADOS")
display(produtos_mais_comprados)

DEZ PRODUTOS MAIS COMPRADOS


,PR_NOME,QUANTIDADE_COMPRAS,PERCENTUAL_DA_BASE
1,PRESUNTO COZIDO,12719,1.73
2,SARDINHA,6610,0.90
3,BANANA,6518,0.89
4,ESCOVA DE DENTE,6518,0.89
5,GEL,6517,0.89
6,PAPINHA INFANTIL,6515,0.89
7,MODELADOR,6505,0.89
8,CERA,6502,0.89
9,CEBOLA,6501,0.89
10,LIMPADOR PERFUMADO,6501,0.89


### Análise complementar — Produtos mais comprados

O Presunto Cozido liderou o ranking, com 12.719 registros de compras, correspondendo a 1,73% da base limpa. O segundo produto foi Sardinha, com 6.610 registros e participação de 0,90%.

Os dez produtos mais comprados representam aproximadamente 9,73% da base. Apesar da forte concentração das compras na categoria Alimentos, nenhum produto individual possui participação dominante. Isso indica que a demanda está distribuída entre diversos produtos do catálogo.

O Presunto Cozido se destaca dos demais produtos, pois possui quase o dobro dos registros apresentados pelo segundo colocado.

In [125]:
# Conta a quantidade de compras registrada para cada produto
abc_produtos = (
    df_limpo
    .groupby("PR_NOME")
    .size()
    .reset_index(name="QUANTIDADE_COMPRAS")
    .sort_values(
        by="QUANTIDADE_COMPRAS",
        ascending=False
    )
    .reset_index(drop=True)
)

# Calcula a participação percentual de cada produto
abc_produtos["PERCENTUAL"] = (
    abc_produtos["QUANTIDADE_COMPRAS"]
    / abc_produtos["QUANTIDADE_COMPRAS"].sum()
    * 100
)

# Calcula o percentual acumulado
abc_produtos["PERCENTUAL_ACUMULADO"] = (
    abc_produtos["PERCENTUAL"].cumsum()
)

# Identifica quantos produtos são necessários para alcançar 80% das compras
quantidade_classe_a = (
    abc_produtos["PERCENTUAL_ACUMULADO"]
    .ge(80)
    .idxmax()
    + 1
)

# Identifica o limite de 95% para formar a classe B
limite_classe_b = (
    abc_produtos["PERCENTUAL_ACUMULADO"]
    .ge(95)
    .idxmax()
    + 1
)

# Classifica os produtos em A, B e C
abc_produtos["CLASSE_ABC"] = "C"
abc_produtos.loc[0:quantidade_classe_a - 1, "CLASSE_ABC"] = "A"
abc_produtos.loc[
    quantidade_classe_a:limite_classe_b - 1,
    "CLASSE_ABC"
] = "B"

# Calcula quanto a classe A representa no catálogo
total_produtos = len(abc_produtos)

percentual_catalogo_classe_a = (
    quantidade_classe_a / total_produtos * 100
)

# Cria um resumo das classes
resumo_abc = (
    abc_produtos
    .groupby("CLASSE_ABC", sort=False)
    .agg(
        QUANTIDADE_PRODUTOS=("PR_NOME", "count"),
        QUANTIDADE_COMPRAS=("QUANTIDADE_COMPRAS", "sum")
    )
    .reset_index()
)

resumo_abc["PERCENTUAL_PRODUTOS"] = (
    resumo_abc["QUANTIDADE_PRODUTOS"]
    / total_produtos
    * 100
).round(2)

resumo_abc["PERCENTUAL_COMPRAS"] = (
    resumo_abc["QUANTIDADE_COMPRAS"]
    / len(df_limpo)
    * 100
).round(2)

print("ANÁLISE ABC DOS PRODUTOS")
print("-" * 50)
print("Total de produtos:", total_produtos)
print("Produtos necessários para alcançar 80% das compras:", quantidade_classe_a)
print(
    "Percentual do catálogo necessário para alcançar 80%:",
    round(percentual_catalogo_classe_a, 2),
    "%"
)

print("\nRESUMO DAS CLASSES:")
display(resumo_abc)

ANÁLISE ABC DOS PRODUTOS
--------------------------------------------------
Total de produtos: 118
Produtos necessários para alcançar 80% das compras: 91
Percentual do catálogo necessário para alcançar 80%: 77.12 %

RESUMO DAS CLASSES:


,CLASSE_ABC,QUANTIDADE_PRODUTOS,QUANTIDADE_COMPRAS,PERCENTUAL_PRODUTOS,PERCENTUAL_COMPRAS
0,A,91,591069,77.12,80.59
1,B,17,107140,14.41,14.61
2,C,10,35238,8.47,4.80


### Análise complementar — Curva ABC dos produtos

A análise ABC foi realizada considerando a frequência dos registros de compras, pois a base não possui informações sobre quantidade vendida, preço ou faturamento.

A Classe A reuniu 91 produtos, equivalentes a 77,12% dos 118 produtos existentes na base. Esses produtos representam 80,59% dos registros de compras.

A Classe B possui 17 produtos, correspondentes a 14,41% do catálogo e 14,61% das compras. A Classe C contém 10 produtos, equivalentes a 8,47% do catálogo e 4,80% das compras.

O resultado não apresenta o comportamento clássico da regra de Pareto, em que aproximadamente 20% dos itens representariam 80% do movimento. Para alcançar cerca de 80% das compras, foram necessários 77,12% dos produtos. Isso demonstra que as compras estão relativamente distribuídas entre grande parte do catálogo, apesar do destaque individual do Presunto Cozido.

A classificação representa frequência de registros de compras e não participação no faturamento, pois a base não disponibiliza valores monetários nem quantidades vendidas.

In [126]:
#Sprint 5 – Relatório, conclusões e documentação
#bjetivo: finalizar a análise, apresentar os resultados e documentar o mini-projeto de forma simples e compreensível.
#Atividades:
#Criar um bloco final com os principais resultados da análise.
#Elaborar de 3 a 6 tópicos de conclusão.
#Informar os problemas encontrados na base.
#Explicar as decisões adotadas na limpeza dos dados.
#Apontar possíveis problemas remanescentes.
#Comentar o código, explicando cada bloco de lógica.
#Revisar a organização e a execução das células do notebook.
#Criar o arquivo README solicitado pela atividade.
#Incluir instruções simples para executar o projeto.
#Resultado esperado:
#Notebook comentado e executável, conclusões apresentadas e arquivo README concluído.
# Gera o relatório consolidado com os principais resultados do projeto
print("=" * 65)
print("RELATÓRIO FINAL — MINI-PROJETO VAREJO")
print("=" * 65)

print("\n1. ESTRUTURA DA BASE")
print("Registros na base original:", len(df))
print("Registros na base limpa:", len(df_limpo))
print("Colunas na base original:", df.shape[1])
print("Colunas na base limpa:", df_limpo.shape[1])

print("\n2. LIMPEZA DOS DADOS")
print("Colunas completamente vazias removidas:", 4)
print("Duplicatas removidas:", len(df) - len(df_limpo))
print("Valores nulos restantes:", df_limpo.isnull().sum().sum())
print("Duplicatas restantes:", df_limpo.duplicated().sum())
print(
    "Registros NÃO INFORMADO:",
    (df_limpo["PR_CAT"] == "NÃO INFORMADO").sum()
)

print("\n3. ESTATÍSTICAS DO NÚMERO DE FILHOS")
print("Média:", round(df_limpo["CL_FHL"].mean(), 2))
print("Mediana:", round(df_limpo["CL_FHL"].median(), 2))
print("Desvio padrão:", round(df_limpo["CL_FHL"].std(), 2))
print("Moda:", df_limpo["CL_FHL"].mode().iloc[0])
print("Máximo:", df_limpo["CL_FHL"].max())
print("Mínimo:", df_limpo["CL_FHL"].min())
print("Contagem:", df_limpo["CL_FHL"].count())

print("\n4. AGRUPAMENTOS OBRIGATÓRIOS")
print("Gênero com mais compras: F — 52,14%")
print("Categoria com mais compras: ALIMENTOS — 52,38%")
print("Categoria NÃO INFORMADO: 0,44%")

print("\n5. ANÁLISES COMPLEMENTARES")
print("Segmento com mais compras: B — 63,88%")
print("Produto mais comprado: PRESUNTO COZIDO — 12.719 registros")
print("Participação do Presunto Cozido: 1,73%")

print("\n6. CURVA ABC POR FREQUÊNCIA DE COMPRAS")
print("Total de produtos:", total_produtos)
print("Produtos da Classe A:", quantidade_classe_a)
print(
    "Percentual do catálogo na Classe A:",
    round(percentual_catalogo_classe_a, 2),
    "%"
)
print("Participação da Classe A nas compras: 80,59%")

print("\nRelatório gerado com sucesso!")
print("=" * 65)

RELATÓRIO FINAL — MINI-PROJETO VAREJO

1. ESTRUTURA DA BASE
Registros na base original: 830000
Registros na base limpa: 733447
Colunas na base original: 14
Colunas na base limpa: 10

2. LIMPEZA DOS DADOS
Colunas completamente vazias removidas: 4
Duplicatas removidas: 96553
Valores nulos restantes: 0
Duplicatas restantes: 0
Registros NÃO INFORMADO: 3228

3. ESTATÍSTICAS DO NÚMERO DE FILHOS
Média: 1.15
Mediana: 0.0
Desvio padrão: 1.42
Moda: 0
Máximo: 4
Mínimo: 0
Contagem: 733447

4. AGRUPAMENTOS OBRIGATÓRIOS
Gênero com mais compras: F — 52,14%
Categoria com mais compras: ALIMENTOS — 52,38%
Categoria NÃO INFORMADO: 0,44%

5. ANÁLISES COMPLEMENTARES
Segmento com mais compras: B — 63,88%
Produto mais comprado: PRESUNTO COZIDO — 12.719 registros
Participação do Presunto Cozido: 1,73%

6. CURVA ABC POR FREQUÊNCIA DE COMPRAS
Total de produtos: 118
Produtos da Classe A: 91
Percentual do catálogo na Classe A: 77.12 %
Participação da Classe A nas compras: 80,59%

Relatório gerado com sucesso!


## Conclusões finais

1. **Qualidade e limpeza da base:** a base original possuía 830.000 registros e 14 colunas. Foram removidas quatro colunas completamente vazias e 96.553 duplicatas, resultando em uma base limpa com 733.447 registros e 10 colunas.

2. **Tratamento dos dados ausentes:** foram encontrados 3.650 registros com #N/D na categoria do produto. Esses valores foram substituídos por NÃO INFORMADO para preservar as demais informações das linhas. Após a retirada das duplicatas, permaneceram 3.228 registros nessa condição, representando apenas 0,44% da base e não alterando as conclusões principais.

3. **Número de filhos:** a média foi de 1,15 filho por registro, enquanto a mediana e a moda foram iguais a zero. Isso indica forte presença de clientes sem filhos nos registros de compras. Entretanto, como um mesmo cliente pode aparecer várias vezes, os resultados representam registros de compras e não necessariamente clientes únicos.

4. **Gênero e categorias:** o gênero feminino apresentou a maior participação nas compras, com 52,14%, contra 47,86% do gênero masculino. A categoria Alimentos concentrou 52,38% das compras, seguida por Higiene e Limpeza. As três categorias somam aproximadamente 88,69% dos registros.

5. **Segmentos e produtos:** o segmento B concentrou 63,88% das compras, mas a base não informa o significado das classificações A, B e C. O Presunto Cozido foi o produto mais comprado, com 12.719 registros, embora tenha representado apenas 1,73% da base.

6. **Curva ABC e limitações remanescentes:** foram necessários 91 dos 118 produtos, equivalentes a 77,12% do catálogo, para alcançar 80,59% das compras. Isso mostra que as compras estão distribuídas entre grande parte dos produtos. A base não possui quantidade vendida, preço, faturamento, número da nota ou identificador da transação; portanto, a Curva ABC representa frequência de registros, e algumas duplicatas removidas podem ter correspondido a compras legítimas de mais de uma unidade.

In [127]:
# Cria o conteúdo do arquivo README do mini-projeto
conteudo_readme = """
# Mini-Projeto — Análise da Base Varejo

## Autor

José Humberto de Souza

**Turma:** T3 — Visualização de Dados e Business Intelligence

## Objetivo

Este mini-projeto tem como objetivo importar, diagnosticar, limpar e analisar a base Varejo.csv utilizando Python e a biblioteca pandas no Google Colab.

## Fonte dos dados

A base foi obtida no Kaggle:

https://www.kaggle.com/datasets/namespaiva/base-varejo

## Etapas realizadas

1. Importação automática da base do Kaggle.
2. Diagnóstico inicial dos registros, colunas e tipos de dados.
3. Padronização dos textos e conversão da coluna DATA para datetime.
4. Identificação e tratamento de valores ausentes.
5. Remoção de colunas completamente vazias.
6. Identificação e remoção de registros duplicados.
7. Cálculo das estatísticas descritivas da coluna número de filhos.
8. Agrupamentos por gênero, categoria e segmento.
9. Ranking dos produtos mais comprados.
10. Análise ABC dos produtos pela frequência de compras.
11. Elaboração do relatório e das conclusões finais.

## Principais resultados

- Base original: 830.000 registros e 14 colunas.
- Base limpa: 733.447 registros e 10 colunas.
- Duplicatas removidas: 96.553.
- Colunas completamente vazias removidas: 4.
- Média de filhos por registro: 1,15.
- Gênero feminino: 52,14% das compras.
- Categoria Alimentos: 52,38% das compras.
- Segmento B: 63,88% das compras.
- Produto mais comprado: Presunto Cozido.
- Foram necessários 91 dos 118 produtos para alcançar 80,59% das compras.

## Como executar

1. Abra o arquivo `Miniprojeto_Varejo_JoseHumberto.ipynb` no Google Colab.
2. No menu superior, clique em **Ambiente de execução**.
3. Selecione **Executar tudo**.
4. Aguarde a importação automática da base do Kaggle e a execução das análises.
5. Confira o relatório e as conclusões apresentados no final do notebook.

É necessário possuir conexão com a internet para que a base seja baixada automaticamente do Kaggle.

## Arquivos do projeto

- `Miniprojeto_Varejo_JoseHumberto.ipynb`: notebook com o código comentado.
- `README_JoseHumberto_T3.md`: documentação do projeto.
- `Varejo_limpo.csv`: base resultante do processo de limpeza.

## Limitações

A base não apresenta quantidade vendida, preço, faturamento, número da nota fiscal ou identificador da transação. Por isso, as análises representam frequência de registros de compras. A análise ABC não representa participação financeira dos produtos.
"""

# Define o nome e o local do arquivo
nome_readme = "/content/README_JoseHumberto_T3.md"

# Salva o conteúdo em formato Markdown
with open(nome_readme, "w", encoding="utf-8") as arquivo:
    arquivo.write(conteudo_readme.strip())

print("README criado com sucesso!")
print("Arquivo:", nome_readme)

README criado com sucesso!
Arquivo: /content/README_JoseHumberto_T3.md


In [128]:
# Importa a ferramenta utilizada para visualizar textos em Markdown
from IPython.display import Markdown, display

# Abre o README e mostra seu conteúdo formatado no notebook
with open(nome_readme, "r", encoding="utf-8") as arquivo:
    conteudo_salvo = arquivo.read()

display(Markdown(conteudo_salvo))

# Mini-Projeto — Análise da Base Varejo

## Autor

José Humberto de Souza

**Turma:** T3 — Visualização de Dados e Business Intelligence

## Objetivo

Este mini-projeto tem como objetivo importar, diagnosticar, limpar e analisar a base Varejo.csv utilizando Python e a biblioteca pandas no Google Colab.

## Fonte dos dados

A base foi obtida no Kaggle:

https://www.kaggle.com/datasets/namespaiva/base-varejo

## Etapas realizadas

1. Importação automática da base do Kaggle.
2. Diagnóstico inicial dos registros, colunas e tipos de dados.
3. Padronização dos textos e conversão da coluna DATA para datetime.
4. Identificação e tratamento de valores ausentes.
5. Remoção de colunas completamente vazias.
6. Identificação e remoção de registros duplicados.
7. Cálculo das estatísticas descritivas da coluna número de filhos.
8. Agrupamentos por gênero, categoria e segmento.
9. Ranking dos produtos mais comprados.
10. Análise ABC dos produtos pela frequência de compras.
11. Elaboração do relatório e das conclusões finais.

## Principais resultados

- Base original: 830.000 registros e 14 colunas.
- Base limpa: 733.447 registros e 10 colunas.
- Duplicatas removidas: 96.553.
- Colunas completamente vazias removidas: 4.
- Média de filhos por registro: 1,15.
- Gênero feminino: 52,14% das compras.
- Categoria Alimentos: 52,38% das compras.
- Segmento B: 63,88% das compras.
- Produto mais comprado: Presunto Cozido.
- Foram necessários 91 dos 118 produtos para alcançar 80,59% das compras.

## Como executar

1. Abra o arquivo `Miniprojeto_Varejo_JoseHumberto.ipynb` no Google Colab.
2. No menu superior, clique em **Ambiente de execução**.
3. Selecione **Executar tudo**.
4. Aguarde a importação automática da base do Kaggle e a execução das análises.
5. Confira o relatório e as conclusões apresentados no final do notebook.

É necessário possuir conexão com a internet para que a base seja baixada automaticamente do Kaggle.

## Arquivos do projeto

- `Miniprojeto_Varejo_JoseHumberto.ipynb`: notebook com o código comentado.
- `README_JoseHumberto_T3.md`: documentação do projeto.
- `Varejo_limpo.csv`: base resultante do processo de limpeza.

## Limitações

A base não apresenta quantidade vendida, preço, faturamento, número da nota fiscal ou identificador da transação. Por isso, as análises representam frequência de registros de compras. A análise ABC não representa participação financeira dos produtos.

In [129]:
# Define o nome e o local do arquivo com a base limpa
caminho_base_limpa = "/content/Varejo_limpo.csv"

# Exporta o DataFrame limpo para CSV
# index=False evita a criação de uma coluna com o índice do pandas
# utf-8-sig facilita a abertura correta dos acentos no Excel
df_limpo.to_csv(
    caminho_base_limpa,
    index=False,
    encoding="utf-8-sig",
    date_format="%Y-%m-%d"
)

# Confere o arquivo exportado
import os

tamanho_mb = os.path.getsize(caminho_base_limpa) / (1024 * 1024)

print("Base limpa exportada com sucesso!")
print("Arquivo:", caminho_base_limpa)
print("Tamanho aproximado:", round(tamanho_mb, 2), "MB")
print("Registros exportados:", len(df_limpo))
print("Colunas exportadas:", df_limpo.shape[1])

Base limpa exportada com sucesso!
Arquivo: /content/Varejo_limpo.csv
Tamanho aproximado: 37.64 MB
Registros exportados: 733447
Colunas exportadas: 10


In [130]:
# Importa a biblioteca utilizada para criar arquivos compactados
import zipfile
import os

# Define o nome do arquivo compactado
caminho_base_compactada = "/content/Varejo_limpo.csv.zip"

# Cria um arquivo ZIP contendo a base limpa em CSV
with zipfile.ZipFile(
    caminho_base_compactada,
    "w",
    compression=zipfile.ZIP_DEFLATED
) as arquivo_zip:
    arquivo_zip.write(
        caminho_base_limpa,
        arcname="Varejo_limpo.csv"
    )

# Confere o tamanho final do arquivo compactado
tamanho_zip_mb = (
    os.path.getsize(caminho_base_compactada)
    / (1024 * 1024)
)

print("Base compactada com sucesso!")
print("Arquivo:", caminho_base_compactada)
print("Tamanho aproximado:", round(tamanho_zip_mb, 2), "MB")

Base compactada com sucesso!
Arquivo: /content/Varejo_limpo.csv.zip
Tamanho aproximado: 3.36 MB


In [131]:
# Atualiza a relação de arquivos no README
conteudo_readme = conteudo_readme.replace(
    "- `Varejo_limpo.csv`: base resultante do processo de limpeza.",
    "- `Varejo_limpo.csv.zip`: base limpa compactada. "
    "Após baixar o arquivo, extraia o conteúdo para obter "
    "o arquivo Varejo_limpo.csv."
)

# Salva novamente o README atualizado
with open(nome_readme, "w", encoding="utf-8") as arquivo:
    arquivo.write(conteudo_readme.strip())

print("README atualizado com sucesso!")
print("Arquivo da base para o GitHub: Varejo_limpo.csv.zip")

README atualizado com sucesso!
Arquivo da base para o GitHub: Varejo_limpo.csv.zip
